require("dotenv").config();
const mongoose = require("mongoose");
const Product = require("./models/Product");
const connectDB = require("./config/db");

const IMG = "/images/products";

const products = [
  // ── T-SHIRTS ──────────────────────────────────────────────
  {
    name: "I Don't Make Mistakes",
    slug: "i-dont-make-mistakes",
    description: "I Don't Make Mistakes. I Date Them. Classic funny quote tee. Soft cotton, relaxed fit.",
    price: 1500,
    images: [`${IMG}/tee-i-dont-make-mistakes.jpg`],
    category: "tshirt",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [{ name: "Black", hex: "#000000" }],
    stock: 50,
    isNew: true,
    isFeatured: true,
  },
  {
    name: "Face Graphic Tee",
    slug: "face-graphic-tee",
    description: "Minimalist abstract face graphic. Bold black print on crisp white cotton.",
    price: 1500,
    images: [`${IMG}/tee-face-graphic.jpg`],
    category: "tshirt",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: [{ name: "White", hex: "#FFFFFF" }],
    stock: 40,
    isNew: true,
    isFeatured: true,
  },
  {
    name: "Hakuna Ma'Vodka",
    slug: "hakuna-mavodka",
    description: "Hakuna Ma'Vodka — It Means No Memories For The Rest Of Your Night. The party tee you need.",
    price: 1500,
    images: [`${IMG}/tee-hakuna-mavodka.jpg`],
    category: "tshirt",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [{ name: "Charcoal", hex: "#4a4a4a" }],
    stock: 35,
    isNew: false,
    isFeatured: true,
  },
  {
    name: "My Worst Nightmare",
    slug: "my-worst-nightmare",
    description: "No WiFi. Dead battery. Loading screen. The tee that speaks to your soul.",
    price: 1500,
    images: [`${IMG}/tee-my-worst-nightmare.jpg`],
    category: "tshirt",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [{ name: "Black", hex: "#000000" }],
    stock: 45,
    isNew: false,
    isFeatured: true,
  },
  {
    name: "Great In Bed",
    slug: "great-in-bed",
    description: "I'm Great In Bed — I Can Sleep For Days! Comfort meets humour in this relaxed fit tee.",
    price: 1500,
    images: [`${IMG}/tee-great-in-bed.jpg`],
    category: "tshirt",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [{ name: "Black", hex: "#000000" }],
    stock: 50,
    isNew: true,
    isFeatured: false,
  },
  {
    name: "Holding A Beer",
    slug: "holding-a-beer",
    description: "I'm Holding A Beer So Yeah, I'm Busy. The only valid excuse.",
    price: 1500,
    images: [`${IMG}/tee-holding-a-beer.jpg`],
    category: "tshirt",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [{ name: "Black", hex: "#000000" }],
    stock: 30,
    isNew: false,
    isFeatured: false,
  },
  {
    name: "It Is What It Is",
    slug: "it-is-what-it-is",
    description: "It Is What It Is — with a smiley. The vibe check tee for those who have accepted life.",
    price: 1500,
    images: [`${IMG}/tee-it-is-what-it-is.jpg`],
    category: "tshirt",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: [{ name: "Black", hex: "#000000" }],
    stock: 60,
    isNew: true,
    isFeatured: false,
  },
  {
    name: "Beer O'Clock",
    slug: "beer-oclock",
    description: "BE:ER O'CLOCK. Digital clock style graphic. It's always beer o'clock somewhere.",
    price: 1500,
    images: [`${IMG}/tee-beer-oclock.jpg`],
    category: "tshirt",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [{ name: "Black", hex: "#000000" }],
    stock: 25,
    isNew: false,
    isFeatured: false,
  },
  {
    name: "Gamer Heartbeat",
    slug: "gamer-heartbeat",
    description: "Controller heartbeat graphic. For those whose heart beats for gaming. Clean white tee.",
    price: 1500,
    images: [`${IMG}/tee-gamer-heartbeat.jpg`],
    category: "tshirt",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: [{ name: "White", hex: "#FFFFFF" }],
    stock: 40,
    isNew: true,
    isFeatured: false,
  },
  {
    name: "I'm Short",
    slug: "im-short",
    description: "If You Think I'm Short, You Should See My Patience. Bold statement. Relaxed fit.",
    price: 1500,
    images: [`${IMG}/tee-im-short.jpg`],
    category: "tshirt",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: [{ name: "Black", hex: "#000000" }],
    stock: 35,
    isNew: false,
    isFeatured: false,
  },
  {
    name: "Are You Drunk?",
    slug: "are-you-drunk",
    description: "Are You Drunk? Yes / No — with a big red X. The conversation starter tee.",
    price: 1500,
    images: [`${IMG}/tee-are-you-drunk.jpg`],
    category: "tshirt",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [{ name: "Black", hex: "#000000" }],
    stock: 30,
    isNew: false,
    isFeatured: false,
  },
  {
    name: "Forget The Dogs",
    slug: "forget-the-dogs",
    description: "Forget The Dogs — Who Let The Idiots Out? The boldest statement tee in the collection.",
    price: 1500,
    images: [`${IMG}/tee-forget-the-dogs.jpg`],
    category: "tshirt",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [{ name: "Black", hex: "#000000" }],
    stock: 20,
    isNew: true,
    isFeatured: false,
  },

  // ── HOODIES ───────────────────────────────────────────────
  {
    name: "Trusting God Hoodie",
    slug: "trusting-god-hoodie",
    description: "I'm Just Out Here Trusting God. Faith-inspired premium hoodie. Soft fleece interior.",
    price: 3500,
    images: [`${IMG}/hoodie-trusting-god.jpg`],
    category: "hoodie",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [{ name: "White", hex: "#FFFFFF" }],
    stock: 25,
    isNew: true,
    isFeatured: true,
  },
  {
    name: "Pray Hoodie",
    slug: "pray-hoodie",
    description: "Pray On It. Pray Over It. Pray Through It. Bold faith hoodie with premium fleece lining.",
    price: 3500,
    images: [`${IMG}/hoodie-pray.jpg`],
    category: "hoodie",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [{ name: "White", hex: "#FFFFFF" }],
    stock: 20,
    isNew: true,
    isFeatured: true,
  },
  {
    name: "Can't Adult Today Hoodie",
    slug: "cant-adult-today-hoodie",
    description: "I Can't Adult Today. Relatable. Cozy. Honest. Premium heavyweight hoodie.",
    price: 3500,
    images: [`${IMG}/hoodie-cant-adult.jpg`],
    category: "hoodie",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [{ name: "Black", hex: "#000000" }],
    stock: 20,
    isNew: false,
    isFeatured: true,
  },
];

async function seed() {
  await connectDB();
  await Product.deleteMany({});
  await Product.insertMany(products);
  console.log(`✓ Seeded ${products.length} products`);
  console.log("  T-Shirts:", products.filter(p => p.category === "tshirt").length);
  console.log("  Hoodies: ", products.filter(p => p.category === "hoodie").length);
  process.exit(0);
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
